steps:
  # Étape 1 : Scan des secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets scan . || echo "No secrets found";

  # Étape 2 : Scan de vulnérabilités des dépendances
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', 'anchore/scan', '.']

  # Étape 3 : Build de l'application Go
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'app-binary', '.']

  # Étape 4 : Build et push de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-binary:${_VERSION}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-binary:${_VERSION}']

substitutions:
  _VERSION: "1.0.0"

options:
  logging: CLOUD_LOGGING_ONLY

