steps:

- name: 'hashicorp/terraform:light'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init
    terraform apply -auto-approve

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-app', '--image', 'gcr.io/$PROJECT_ID/my-app', '--platform', 'managed']

options:
  logging: CLOUD_LOGGING_ONLY
