steps:
  # Step 1: Verification des "secrets"
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - >
        gcloud secrets scan . || echo "No secrets found";

  # Step 2: Verification des vulnérabilts potentielles
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - 'anchore/scan'
      - '.'

  # Step 3: Build de l'app
  - name: 'gcr.io/cloud-builders/go'
    args:
      - 'build'
      - '-o'
      - 'app-binary'

  # Step 4: Envoie vers "l'artefact registry"
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/go-app:${_VERSION}'

# Validation du Formattage du Terraform
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform fmt -recursive && terraform validate;

  # Terraform Init and Apply
  - name: 'hashicorp/terraform'
    args:
      - 'init'
  - name: 'hashicorp/terraform'
    args:
      - 'apply'
      - '-auto-approve'

substitutions:
  _VERSION: "1.0.0"

options:
  logging: CLOUD_LOGGING_ONLY

